spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/documind
    username: postgres
    password: abhi0807
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

documind:
  clone:
    base-path: A:/documind/data/repos

server:
  port: 8080